#!/bin/bash

function boshenv() {
    if [ -z "$1" ]; then
        set -x
        export BOSH_ENVIRONMENT=malbec_bucc
        set +x
        return
    fi
    if [ "$1" = 'info' ]; then
        found="none"
        OLDIFS="$IFS"
        IFS='
'
        for x in $(compgen -A variable | grep --color=never -E '^BOSH' | grep --color=never -E -v 'BACKUP$')
        do
            found="some"
            local varValue=${!x}
            if [[ "$x" =~ (PASS$|PASSWORD$|CREDENTIAL$|SECRET$|CERT$|CERTIFICATE$) ]]; then varValue='<redacted>' ; fi
            echo "${x}=${varValue}"
        done
        IFS="$OLDIFS"
        if [ "$found" = "none" ]; then echo "none." ; fi
        return
    fi
    if [ "$1" = 'unset' ]; then
        export BOSH_ENVIRONMENT_BACKUP=$BOSH_ENVIRONMENT ; unset BOSH_ENVIRONMENT
        export BOSH_DEPLOYMENT_BACKUP=$BOSH_DEPLOYMENT ; unset BOSH_DEPLOYMENT
        export BOSH_CA_CERT_BACKUP=$BOSH_CA_CERT ; unset BOSH_CA_CERT
        export BOSH_GW_HOST_BACKUP=$BOSH_GW_HOST ; unset BOSH_GW_HOST
        export BOSH_GW_USER_BACKUP=$BOSH_GW_USER ; unset BOSH_GW_USER
        export BOSH_GW_PRIVATE_KEY_BACKUP=$BOSH_GW_PRIVATE_KEY ; unset BOSH_GW_PRIVATE_KEY
        export BOSH_CLIENT_BACKUP=$BOSH_CLIENT ; unset BOSH_CLIENT
        export BOSH_CLIENT_SECRET_BACKUP=$BOSH_CLIENT_SECRET ; unset BOSH_CLIENT_SECRET
        export BOSH_ALL_PROXY_BACKUP=$BOSH_ALL_PROXY ; unset BOSH_ALL_PROXY
        return
    fi
    if [ "$1" = '-e' ]; then
        if [ -z "$2" ]; then
            >&2 echo "no bosh env given"
            return
        else
            set -x
            export BOSH_ENVIRONMENT=$2
            set +x
            shift
            shift
        fi
    fi
    if [ "$1" = "-d" ]; then
        if [ -z "$2" ]; then
            >&2 echo "no deployment given"
            return
        else
            set -x
            export BOSH_DEPLOYMENT=$2
            set +x
            if [ -z "$BOSH_ENVIRONMENT" ]; then
                >&2 echo "carefull! no BOSH_ENVIRONMENT is set!!!"
            fi
            shift
            shift
        fi
    fi
}
