#!/bin/bash

echo "$(date -Is) env/jumpbox-boshrelease-env/install start..." >> $HOME/install.log
set -e

mkdir -p ~/bin
sudo mkdir -p /workarea
sudo chown admin:staff /workarea
sudo chmod 775 /workarea
touch ${HOME}/.bashrc

sudo apt --yes install apt-transport-https

grep -q "source $HOME/env/bashrc" ~/.bashrc || echo "source $HOME/env/bashrc" >> ${HOME}/.bashrc

wget -qO - https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key | sudo apt-key add -
echo "deb http://apt.starkandwayne.com stable main" | sudo tee /etc/apt/sources.list.d/starkandwayne.list

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo touch /etc/apt/sources.list.d/kubernetes.list 
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"


sudo apt update
apt-cache policy docker-ce


if [ -x "env/setup.sh" ];then env/setup.sh ; fi
echo "$(date -Is) env/jumpbox-boshrelease-env/install sourcing $HOME/.bashrc end." >> $HOME/install.log
source $HOME/.bashrc
